---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 837442801-ukwmn1CNRLUCavYFGMG2p855dB7e7A2dV99Ft0vh
:access_token_secret: 150CWFQ3PRur1CtZ453cmIYs4FQj1EpekVXDBhuWuR1t0
